### ISSUE TITLE
Cropping

### ISSUE THREAD

**Issue by felschr** [PeculiarVentures/GammaCV#145]
I'd like to use GammaCV to crop an imag on the GPU. So far I only found `perspectiveProjection` which I can use for cropping. My guess is that this wouldn't be as fast as a simpler cropping operation.
Is there a better way to do this? I'm new to computer vision & not very familiar with graphics programming.

**Comment by WorldThirteen** [comment]
@felschr, `perspectiveProjection` is a universal tool and can be used in simple crop cases too, but it might be overweight for a simple cropping use case.
GammaCV has no built-in crop operation, but it is possible to create your own. The implementation will depend on the details of your requirements, such like:
- do you want to change the crop coordinates "on the fly";
- does the size of the resulting image will always be the same as crop coordinates;
- etc.

Here is a guide on how to create an operation: https://gammacv.com/docs/create_operation.

The sample crop operation for a simple case might look like:

kernel.glsl
```glsl
vec4 operation(float y, float x) {
  return pickValue_tSrc(y + float(CY), x + float(CX));
}
```

crop.js
```js
import * as gm from 'gammacv';
import kernel from './kernel.glsl';

export default (tSrc, x, y, w, h) => new gm.RegisterOperation('crop')
  .Input('tSrc', tSrc.dtype)
  .Output(tSrc.dtype)
  .Constant('CX', x)
  .Constant('CY', y)
  .LoadChunk('pickValue')
  .GLSLKernel(kernel)
  .SetShapeFn(() => [h, w, 4])
  .Compile({ tSrc });
```

This sample has `kernel.glsl`, as a separate file for syntax highlight, if you are not using a bundler that could load glsl as js strings, then you should put the content of kernel glsl as a string variable. This implementation is just a sample, wasn't debugged, and does not contain boundary state control.

Here is this sample on CodePen: https://codepen.io/WorldThirteen/pen/gOozMVo.

**Comment by WorldThirteen** [comment]
Since we have no near-tearm plans to create a built-in crop operation, I am closing an issue.
