### ISSUE TITLE
Upsample and Downsample examples not working

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/GammaCV#36]
![image](https://user-images.githubusercontent.com/1619279/50669649-41bfe580-0f7b-11e9-90af-a0c151d854db.png)
![image](https://user-images.githubusercontent.com/1619279/50669663-5c925a00-0f7b-11e9-93d2-1622cb13d848.png)

**Comment by WorldThirteen** [comment]
@rmhrisk, Please provide more info about your graphics hardware, the easiest way to get the full report is:
- open `https://browserleaks.com/webgl`
- use camera icon in top right to get the report in png
- share report with us

**Comment by apilguk** [comment]
the same for me

**Comment by tetreault** [comment]
This has been recreated on our end on older macbook pros (2012) but it is fine on my 2016 macbook pro

**Comment by rmhrisk** [comment]
I had a older 2012 Mac at the time.

**Comment by WorldThirteen** [comment]
@rmhrisk, do you still own that mac to check the latest version?
