### ISSUE TITLE
Does this work in Vue/Nuxt?

### ISSUE THREAD

**Issue by tetreault** [PeculiarVentures/GammaCV#42]
Hello!

GammaCV is amazing. Your demos work very well on desktop and mobile safari. If I try to use GammaCV in Nuxt/Vue it breaks at import. I'd love to use this in our projects at work. If you have any advice I'd be happy to try and help make this work in this context. 

<img width="1319" alt="Screen Shot 2019-03-12 at 7 58 51 PM" src="https://user-images.githubusercontent.com/5934354/54244112-84fd7e00-4501-11e9-908b-bff1e603140d.png">

**Comment by rmhrisk** [comment]
We have not used it in Vue but would be happy to accept a PR that resolved the issue or answer any questions. Nothing I can think of should prevent it from working in that context.

**Comment by tetreault** [comment]
Resolved it on my end, was my mistake!

**Comment by apilguk** [comment]
Thanks for the response
Ill glad to help you if have more questions

**Comment by tetreault** [comment]
Thanks @apilguk ! So i have it working on  a static image in Nuxt, but is there some straightforward example of code on using this on video? You guys do it on the examples section of the site, and I have been trying to go through all the files in the app directory of the GammaCV repo but its a lot of files... haha 

I need to take the stream I create from `new gm.CaptureVideo` and run operations on it and draw it to full screen canvas for the user. Do you guys have a short example code that is not just for static image like in the GammaCV docs? Maybe it is just me, but some advice would be useful!

**Comment by rmhrisk** [comment]
@tetreault happy to help but can you file a separate issue so others can find answers as they search ore easily?

**Comment by tetreault** [comment]
Of course @rmhrisk !

**Comment by tetreault** [comment]
I think I might have made some progress but its not functional yet @rmhrisk I will open the issue soon  when I have some code to show in hopes that it helps show what I'm trying to accomplish with pixelwise_math operation
