### ISSUE TITLE
[demo help] GammaCV for webcam

### ISSUE THREAD

**Issue by tetreault** [PeculiarVentures/GammaCV#44]
Hello, 

Earlier I asked about some assistance on a demo using the webcam, in particular I'm trying to use the the pixelwise_math "sub" example in a project. I'm using a [single file vue component](https://vuejs.org/v2/guide/single-file-components.html). 

I was trying to piece it together from pieces of these two files: 
- https://github.com/PeculiarVentures/GammaCV/blob/e287f92286da09748489805ebb7fceb48018c1ef/app/src/containers/example/example_container.jsx
- https://github.com/PeculiarVentures/GammaCV/blob/e287f92286da09748489805ebb7fceb48018c1ef/app/src/examples/math_pixelwise.js

Any assistance would be great! Here's the  script part of the component I tossed together quickly but its obviously not functional. I seem to get valid instances from `gm.Tensor` and  `gm.Session` and `gm.CaptureVideo` works fine but my `updateVideoCanvas` function throws an error when it hits the lines around `gm.tensorClone` or `gm.canvasFromTensor`.

```javascript
<script>
let gm;
if (process.browser) {
  gm = require("gammacv");
}

export default {
  data() {
    return {
      currFrameTensor: undefined,
      prevFrameTensor: undefined,
      outputTensor: undefined,
      modifiedCanvas: undefined,
      stream: undefined,
      session: undefined,
      operation: undefined
    };
  },
  mounted() {
    this.modifiedCanvas = this.$refs.modifiedCanvasEl;

    // create the tensors with the dimensions of the canvas the output will go to
    this.currFrameTensor = new gm.Tensor("uint8", [
      this.modifiedCanvas.clientWidth,
      this.modifiedCanvas.clientHeight,
      4
    ]);

    this.prevFrameTensor = new gm.Tensor("uint8", [
      this.modifiedCanvas.clientWidth,
      this.modifiedCanvas.clientHeight,
      4
    ]);
  },
  methods: {
    startCam() {
      this.session = new gm.Session();
      this.stream = new gm.CaptureVideo(
        this.modifiedCanvas.clientWidth,
        this.modifiedCanvas.clientHeight
      );
      this.operation = gm.sub(this.currFrameTensor, this.prevFrameTensor);

      // start video from CaptureVideo() and run RAF loop
      this.stream
        .start()
        .then(() => {
          this.outputTensor = gm.tensorFrom(this.operation);
          this.session.init(this.operation);
          this.stream.getImageBuffer(this.currFrameTensor);
          this.updateVideoCanvas();
        })
        .catch(() => {
          this.stop(true);
        });
    },
    updateVideoCanvas() {
      gm.clearCanvas(this.modifiedCanvas);
      gm.tensorClone(this.currFrameTensor, this.prevFrameTensor);
      this.stream.getImageBuffer(this.currFrameTensor);
      gm.tensorClone(this.currFrameTensor, this.prevFrameTensor);
      gm.canvasFromTensor(this.modifiedCanvas, this.currFrameTensor);
      requestAnimationFrame(this.updateVideoCanvas);
    }
  }
};
</script>
```

**Comment by tetreault** [comment]
Correction - I have it functional, however it is giving me results very different from the official GammaCV demo on the website. Here's a screenshot. 

<img width="1414" alt="Screen Shot 2019-03-13 at 9 57 59 PM" src="https://user-images.githubusercontent.com/5934354/54325988-302e3600-45db-11e9-9458-d784a1c742a6.png">

**Comment by WorldThirteen** [comment]
Hi @tetreault!
Looks like the problem is here:
```
this.currFrameTensor = new gm.Tensor("uint8", [
  this.modifiedCanvas.clientWidth,
  this.modifiedCanvas.clientHeight,
  4
]);
``` 
Since the gm.Tensor, and browser's `getImageData` use Row-major ordering for multidimentional data ([Wiki](https://en.wikipedia.org/wiki/Row-_and_column-major_order)), the first element in shape (second argument) must be height of the image, like:
```
this.currFrameTensor = new gm.Tensor("uint8", [
  this.modifiedCanvas.clientHeight,
  this.modifiedCanvas.clientWidth,
  4
]);
``` 
So each tensor that represents the image should have shape: `[height, width, 4]`.
Hope this helps!
Do you think this should be highlighted in our docs?
I didn't try to check it using your code. If my suggestion does not help I'll try later today.

**Comment by tetreault** [comment]
Hello @WorldThirteen thank you for the time and the help! 

Unfortunately switching the width and height parameters did not produce the result I was hoping for seen in the pixelwise_math demo. I wanted to save you some time and I created a demo repo on github for you to check out - the file to look at is `pages/index.vue`. Here's the repo link: https://github.com/tetreault/gammacv-nuxt-demo

When I used your suggestion the canvas just displayed basically unmodified frames form the webcam feed. I've not done much work with tensors and am new to GammaCV so I am sure the mistake I am making is a simple one!

**Comment by tetreault** [comment]
@WorldThirteen after merging your PR it works! It looks like my mistake was a small stupid one 😄 

Thank you for the help! I'm excited to use gammacv in some upcoming work!

**Comment by tetreault** [comment]
I will also keep the gammacv nuxt repo up that I linked in my prior comment, in case anyone in the future needs it!

**Comment by rmhrisk** [comment]
@tetreault we would love to hear about the projects your doing with GammaCV as it will influence how we add to it in the future.

**Comment by tetreault** [comment]
Sure thing! I'd be happy to provide feedback. Currently I'm just prototyping out an experience pending client approval, but if we get client approval on the design and prototype I'm happy to send through an email discussing the project at a high level. Is the email in your github bio a good one to send this email to later on @rmhrisk ?

**Comment by tetreault** [comment]
As for GammaCV docs, I do think in my opinion having a small simple isolated snippet of code under "Getting Started" would be a good head start, similar to how you have it for handling static images/chaining operations.

**Comment by rmhrisk** [comment]
Sounds good. As for a sample, mind providing a PR?

**Comment by tetreault** [comment]
no problem!
