### ISSUE TITLE
StrokeWidthTransform (swt) example

### ISSUE THREAD

**Issue by alenmestrov** [PeculiarVentures/GammaCV#58]
Hi,

sorry if I'm posting this in the wrong place but do you maybe have an example of a call for .swt() function?
I'm struggling to set it up and I can't find a reference to its implementation in any given example.

Thank you in advance and sorry for troubling.

**Comment by apilguk** [comment]
Hi,

Here you can find an example of Stroke Width Transform with visualization
https://codepen.io/apilguk/pen/OJVzGEG?editors=0010

![image](https://user-images.githubusercontent.com/5960711/76338398-4dd2d000-6301-11ea-9001-2187c956b2b9.png)

**Comment by rmhrisk** [comment]
@apilguk please add a work item to add this as an example in the GammaCV website/documentation.

**Comment by alenmestrov** [comment]
@apilguk Thank you very much!

**Comment by apilguk** [comment]
@alenmestrov you are welcome, can we close ?

**Comment by rmhrisk** [comment]
Please keep open until docs are updated

**Comment by WorldThirteen** [comment]
The SWT example is available here https://gammacv.com/examples/swt and its source code available here: https://github.com/PeculiarVentures/GammaCV/blob/master/app/sources/examples/swt.js
