### ISSUE TITLE
Maybe just a dumb doubt

### ISSUE THREAD

**Issue by Fercho120** [PeculiarVentures/GammaCV#59]
Hi I'm quite new to web development and I have a doubt: As I understand GammaCV works on front-end, using WebGL, WASM, etc. but tutorial says that I must install it using node's package manager npm?! I though node.js was a back-end technology. 
Should I use a node-based local server for installing it and then loading the result on my webpage?
I'm quite confused as my closest experience is using OpenCv.js which I could include into my page via their nightly release at their CDN or compiling the files myself using Emscripten and then uploading it to the server.

How can I include your library on my project?

Sorry if this question is dumb but I'm quite confused, however maybe you could help some noobs like me on starting using your library if this kind of obvious steps are shown on the tutorial.

Thank you for your work!

**Comment by rmhrisk** [comment]
You understand GamaCV correctly.

https://www.agiliq.com/blog/2019/01/using-npm-to-manage-frontend-libraries/

**Comment by WorldThirteen** [comment]
If you don't want to use npm for your frontend, you are able to download the latest release from https://github.com/PeculiarVentures/GammaCV/releases. You are interested in dist.zip.
Then you could connect as a script:
```html
<script src="index.min.js"></script>
```
The global object `gm` will appear for your usage as soon as script loaded.

**Comment by WorldThirteen** [comment]
The solution was proposed, closing since inactive.
Feel free to reopen the issue if you have related questions about the GammaCV library.
