### ISSUE TITLE
Sry for distrub

### ISSUE THREAD

**Issue by surajparkar787** [PeculiarVentures/GammaCV#60]
, how i full setup of canny image, plz help me, i download the labrary , canny images example aslo copy on server,

**Comment by rmhrisk** [comment]
Suraj,

Sorry, I do not fully nderstand the question.

GammaCV is fully client-side and has no need for a server.

Have you seen the samples? https://gammacv.com/examples/canny_edges  + https://github.com/PeculiarVentures/GammaCV/blob/master/app/src/examples/canny_edges.js

**Comment by surajparkar787** [comment]
Hey  how to make canny image inverse
And how to get output image on variable

**Comment by rmhrisk** [comment]
Here is how to get the contents of a canvas object: https://stackoverflow.com/questions/8126623/downloading-canvas-element-to-an-image

Here is how to flip an image in a canvas object: https://stackoverflow.com/questions/3129099/how-to-flip-images-horizontally-with-html5

**Comment by WorldThirteen** [comment]
Closing since inactive, feel free to reopen the issue if you have related questions about the GammaCV library.
