### ISSUE TITLE
Spell mistake?

### ISSUE THREAD

**Issue by xixilive** [PeculiarVentures/GammaCV#62]
https://github.com/PeculiarVentures/GammaCV/blob/b06c9ae24208637076d6e8c5a8b1ceddbff79521/lib/program/tensor.js#L145

does `relese` means `release` ?

**Comment by WorldThirteen** [comment]
@xixilive, thanks for pointing, we will fix with the saving of backward capability in the nearest release.

**Comment by WorldThirteen** [comment]
We have fixed this in the latest release https://github.com/PeculiarVentures/GammaCV/releases/tag/v0.4.0.
