### ISSUE TITLE
Error handling for uninitialized operation

### ISSUE THREAD

**Issue by apilguk** [PeculiarVentures/GammaCV#7]
Sometimes happens to me I forgetting to initialize operation for a specific session `sess.init(op)` and then trying to run it `sess.runOp(op, frame, out)`. Currently, we have no any message and error is really unclear what is happening

**Comment by WorldThirteen** [comment]
This was released in [v0.5.5](https://github.com/PeculiarVentures/GammaCV/releases/tag/v0.5.0)
