### ISSUE TITLE
The use of eval causes problems for bundlers and minification, use new Function instead.

### ISSUE THREAD

**Issue by euan-smith** [PeculiarVentures/GammaCV#75]
In the functions `tensorInvert` and `flipTensor` you are using the `eval` function.  The way you are using it could, I think, be replaced by a `new Function`.  The use of eval can cause, in particular, issues for [Rollup](https://rollupjs.org) (which throws a few warnings if gammaCV is imported) - see for more information [here](https://rollupjs.org/guide/en/#avoiding-eval).  Given that you are actually using eval to create a function it would also seem better practice to use new Function.

**Comment by WorldThirteen** [comment]
@euan-smith, thanks for the issue! We will investigate your proposal and provide an update soon.

**Comment by WorldThirteen** [comment]
Happy to notify, that a fix for this released in v0.5.0. GammaCV is no longer uses `eval` for performance optimizations, `new Function` used instead.
