### ISSUE TITLE
Types mistake

### ISSUE THREAD

**Issue by donskov** [PeculiarVentures/GammaCV#91]
## Current Behavior

Method `start` of `CaptureVideo` class returns type `void`.

```ts
export class CaptureVideo {
  ...
  start(deviceID?: string, exactFacingMode?: string): void;
}
```

https://github.com/PeculiarVentures/GammaCV/blob/master/lib/index.d.ts#L11

## Expected Behavior

Method `start` of `CaptureVideo` returns type `Promise<void>`.

## Steps to Reproduce

```ts
const stream = new gm.CaptureVideo(100, 100);

console.og(stream.start() instanceof Promise) // => true
```

**Comment by WorldThirteen** [comment]
Fixed in 0.5.1.
